# -*- coding: utf-8 -*-

"""
pytorch.ipynb

Automatically generated by Colaboratory.

"""

# refer to https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html#defining-the-dataset

# PART 2: Constructs a Faster R-CNN model with a ResNet-50-FPN backbone. pre-trained on COCO
# ==================================
import torchvision

model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)

# replace the classifier with user-defined num_classes 
num_classes = 2  # 1 background + 1 class

in_features = model.roi_heads.box_predictor.cls_score.in_features
# print(model)
# FasterRCNN(
#   (transform): GeneralizedRCNNTransform(
#       Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
#       Resize(min_size=(800,), max_size=1333, mode='bilinear')
#   )
#   (backbone): BackboneWithFPN(
#   ...  
#   ...  
#   (roi_heads): RoIHeads(
#     (box_roi_pool): MultiScaleRoIAlign(featmap_names=['0', '1', '2', '3'], output_size=(7, 7), sampling_ratio=2)
#     (box_head): TwoMLPHead(
#       (fc6): Linear(in_features=12544, out_features=1024, bias=True)
#       (fc7): Linear(in_features=1024, out_features=1024, bias=True)
#     )
#     (box_predictor): FastRCNNPredictor(
#       (cls_score): Linear(in_features=1024, out_features=91, bias=True)
#       (bbox_pred): Linear(in_features=1024, out_features=364, bias=True)
#     )
#   )
# )

# replace the pre-trained head with a new one
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
# print(model)
#   ...  
#   (roi_heads): RoIHeads(
#     (box_roi_pool): MultiScaleRoIAlign(featmap_names=['0', '1', '2', '3'], output_size=(7, 7), sampling_ratio=2)
#     (box_head): TwoMLPHead(
#       (fc6): Linear(in_features=12544, out_features=1024, bias=True)
#       (fc7): Linear(in_features=1024, out_features=1024, bias=True)
#     )
#     (box_predictor): FastRCNNPredictor(
#       (cls_score): Linear(in_features=1024, out_features=2, bias=True)
#       (bbox_pred): Linear(in_features=1024, out_features=8, bias=True)
#     )
#   )
# )
